version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16
    volumes:
      - ..:/workspace:cached
    env_file: ../.env
    command: sleep infinity
    network_mode: service:mariadb

  mariadb:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: ../.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb-data:
